version: '3.1'

services:

  database:
    image: mysql
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker-practice
    container_name: mysql-container
    volumes:
      - mysql-volume:/var/lib/mysql

  server-app:
    build: .
    image: server
    ports:
      - 6060:9090
    container_name: server-container
    depends_on:
      - database

  client-app:
    build: .
    ports:
      - 7070:8080
    container_name: client-container
    depends_on:
      - server-app

volumes:
  mysql-volume:

