version: '3.1'

services:

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: client
    container_name: mysql-cont
    volumes:
      - mysql-volume:/var/lib/mysql

  server-app:
    build: .
    image: server:v1
    ports:
      - 6060:9090
    container_name: server-container
    depends_on:
      - database

  client-app:
    image: client:v1
    ports:
      - 8686:8081
    container_name: client-container
    depends_on:
      - server-app

volumes:
  mysql-volume:

